module Exercise5 where

import Exercise4 (isPermutation)
import Data.List (permutations)
import Test.QuickCheck

-- Time spent: 120mins
-- Dependencies: Exercise4 (isPermutation), Data.List (permutations), Test.QuickCheck

isDerangement :: Eq a => [a] -> [a] -> Bool
isDerangement xs ys = isPermutation xs ys && all (==True) (zipWith (/=) xs ys)

deran :: Int -> [[Int]]
deran n = filter (isDerangement xs) (permutations xs)
  where xs = [0..n-1]

-- Properties for strength comparison
prop_deran :: ([Int], [Int]) -> Bool
prop_deran (xs, ys) = isDerangement xs ys

prop_perm :: ([Int], [Int]) -> Bool
prop_perm (xs, ys) = isPermutation xs ys

prop_noFixed :: ([Int], [Int]) -> Bool
prop_noFixed (xs, ys) = length xs == length ys && all (==True) (zipWith (/=) xs ys)

prop_sameLen :: ([Int], [Int]) -> Bool
prop_sameLen (xs, ys) = length xs == length ys

-- QuickCheck
-- Property: every list generated by deran is a valid derangement
prop_deranAllValid :: Property
prop_deranAllValid = forAll (choose (0, 5)) (\n -> all (isDerangement [0..n-1]) (deran n))

main :: IO ()
main = do
  putStrLn "Exercise 5:"
  putStrLn "Testing isDerangement on chosen lists:"
  putStrLn $ "isDerangement [1,2,3] [2,3,1]: " ++ show (isDerangement [1,2,3] [2,3,1])
  putStrLn $ "isDerangement [1,2,3] [1,3,2]: " ++ show (isDerangement [1,2,3] [1,3,2])
  putStrLn $ "isDerangement [1,2,3] [1,2,3]: " ++ show (isDerangement [1,2,3] [1,2,3])
  putStrLn $ "isDerangement [1,2,3] [4,5,6]: " ++ show (isDerangement [1,2,3] [4,5,6])
  putStrLn $ "isDerangement [1,2,3] [2,1]: " ++ show (isDerangement [1,2,3] [2,1])

  putStrLn "\nGenerating derangements with deran:"
  putStrLn $ "deran 0 = " ++ show (deran 0)
  putStrLn $ "deran 1 = " ++ show (deran 1)
  putStrLn $ "deran 2 = " ++ show (deran 2)
  putStrLn $ "deran 3 = " ++ show (deran 3)

  putStrLn "\nQuickCheck tests:"
  putStrLn "Property: all generated lists are derangements:"
  quickCheck prop_deranAllValid

-- === Output ===
-- Exercise 5:
-- Testing isDerangement on chosen lists:
-- isDerangement [1,2,3] [2,3,1]: True
-- isDerangement [1,2,3] [1,3,2]: False
-- isDerangement [1,2,3] [1,2,3]: False
-- isDerangement [1,2,3] [4,5,6]: False
-- isDerangement [1,2,3] [2,1]: False

-- Generating derangements with deran:
-- deran 0 = [[]]
-- deran 1 = []
-- deran 2 = [[1,0]]
-- deran 3 = [[1,2,0],[2,0,1]]

-- QuickCheck tests:
-- Property: all generated lists are derangements:
-- +++ OK, passed 100 tests.

-- Provide an ordered list of properties by strength using the weaker and stronger definitions.

-- prop_deran is strictly stronger than both prop_perm and prop_noFixed, since it's using them in its logic.
-- prop_perm and prop_noFixed are strictly stronger than prop_sameLen, since once again, both use the length check in their logic.
-- prop_perm and prop_noFixed are not comparable.

-- How can you automate the test process?

-- We've automated testing with QuickCheck. Specifically, we've been verifying whether
-- every permutation generated by `deran n` satisfies `isDerangement [0..n-1]`.